version: '{build}'
image: Visual Studio 2017
build_script:
- ps: .\Build.ps1
artifacts:
- path: 'artifacts\**'
deploy:
- provider: NuGet
  api_key:
    secure: e2YzBo0FKc0wB3m/U04+RlABYuZleLKOm+gOETUMlwQs6LwuNvjVNc5s19sFTMjT
  on:
    APPVEYOR_REPO_TAG: true