version: '{build}'
image: Visual Studio 2019
build_script:
- ps: .\Build.ps1
artifacts:
- path: 'artifacts\**'
deploy:
- provider: NuGet
  api_key:
    secure: vwKBncodd9gfnaD3nYDZpL5woKkBYGmONp8bNA7WHx9PatPAbgoJb9zLH8qvHbnS
  on:
    APPVEYOR_REPO_TAG: true